title: Sudhin Suresh
email: mail@sudhinsuresh.com
description: >- # this means to ignore newlines until "baseurl:"
  Sudhin Suresh Personal Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sudhinsuresh.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-146053264-1

github_username:  sudhinsr
linkedin_username: sudhinsureshr

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

disqus:
  shortname:  sudhinsureshcom

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
